version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: finance_db
    environment:
      POSTGRES_DB: financetracker
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: financepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: